# Generated by Django 3.1.7 on 2021-02-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Psychotherapists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.TextField(default='N/A')),
                ('metod', models.TextField(default='N/A')),
            ],
        ),
    ]
