# Generated by Django 3.1.7 on 2021-02-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychotherapists',
            name='id',
            field=models.CharField(max_length=18, primary_key=True, serialize=False),
        ),
    ]
