# Generated by Django 3.1.7 on 2021-02-24 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0003_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='description',
            new_name='event',
        ),
    ]
