# Generated by Django 3.1.7 on 2021-02-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0004_auto_20210224_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='event',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='psychotherapists',
            name='metod',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='psychotherapists',
            name='photo',
            field=models.TextField(),
        ),
    ]
